### ISSUE TITLE
Docker stopped after several seconds

### ISSUE THREAD

**Issue by b0nn1e** [db1000n-coordinators/LoadTestConfig#2]
Hi!

After several second docker has been stopped. Log below

```
root@vds2140872:~# docker run ghcr.io/arriven/db1000n
2022/03/03 16:56:31 178.248.236.218 is already an IP address, skipping DNS resolution
2022/03/03 16:56:31 178.248.236.218 is already an IP address, skipping DNS resolution
⠧ Flood is in progress, target=178.248.236.218:80, floodType=random, payloadLength=1000 (5.3 MB, 383.465 kB/s)
root@vds2140872:~# 
```

I saw the same problem in telegram chat.

`у меня в докере на АВС то же самое, пару секунд и падает Exited (137) 10 seconds ago`

**Comment by mishgu** [comment]
@Arriven who is responsible for update the config file?

**Comment by Arriven** [comment]
@mishgu I've almost finished instructing admins (human interactions take time due to war in our country). The config should become updated very soon
